-- Private server-written records for crop-photo assessments and direct produce sales.
CREATE TABLE IF NOT EXISTS public.crop_disease_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT,
    crop_name VARCHAR(100) NOT NULL,
    symptoms TEXT NOT NULL DEFAULT '',
    language VARCHAR(10) NOT NULL DEFAULT 'en',
    image_path TEXT NOT NULL,
    assessment_json JSONB NOT NULL,
    ai_model VARCHAR(80) NOT NULL DEFAULT 'Gemini Vision',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_crop_disease_reports_farm_created
    ON public.crop_disease_reports (farm_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.produce_listings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    farm_id BIGINT,
    seller_name VARCHAR(100) NOT NULL,
    seller_phone VARCHAR(20) NOT NULL,
    crop_name VARCHAR(100) NOT NULL,
    quantity_kg NUMERIC(12, 2) NOT NULL CHECK (quantity_kg > 0),
    price_per_kg NUMERIC(12, 2) NOT NULL CHECK (price_per_kg > 0),
    location VARCHAR(180) NOT NULL,
    harvest_date DATE,
    quality_grade VARCHAR(80) NOT NULL DEFAULT 'Not graded',
    details TEXT NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'sold')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_produce_listings_available_created
    ON public.produce_listings (status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.produce_purchase_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id UUID NOT NULL REFERENCES public.produce_listings(id),
    buyer_name VARCHAR(100) NOT NULL,
    buyer_phone VARCHAR(20) NOT NULL,
    seller_name VARCHAR(100) NOT NULL,
    seller_phone VARCHAR(20) NOT NULL,
    crop_name VARCHAR(100) NOT NULL,
    quantity_kg NUMERIC(12, 2) NOT NULL CHECK (quantity_kg > 0),
    price_per_kg NUMERIC(12, 2) NOT NULL CHECK (price_per_kg > 0),
    total_amount NUMERIC(14, 2) NOT NULL CHECK (total_amount > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'requested' CHECK (status IN ('requested', 'accepted', 'completed', 'cancelled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_produce_purchase_requests_listing_created
    ON public.produce_purchase_requests (listing_id, created_at DESC);

ALTER TABLE public.crop_disease_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.produce_listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.produce_purchase_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.crop_disease_reports, public.produce_listings, public.produce_purchase_requests FROM anon, authenticated;
GRANT SELECT, INSERT ON public.crop_disease_reports, public.produce_listings TO service_role;
GRANT SELECT, INSERT ON public.produce_purchase_requests TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.crop_disease_reports_id_seq TO service_role;

-- Images are private; only the backend's service key can add/read objects.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('crop-disease-images', 'crop-disease-images', FALSE, 6291456, ARRAY['image/jpeg', 'image/png', 'image/webp'])
ON CONFLICT (id) DO UPDATE SET public = FALSE, file_size_limit = 6291456,
    allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp'];

-- A single atomic function reserves stock and records the direct buyer request.
CREATE OR REPLACE FUNCTION public.request_produce_purchase(
    p_listing_id UUID,
    p_buyer_name TEXT,
    p_buyer_phone TEXT,
    p_quantity_kg NUMERIC
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    listing public.produce_listings%ROWTYPE;
    request_id UUID;
    remaining NUMERIC(12, 2);
BEGIN
    IF p_quantity_kg IS NULL OR p_quantity_kg <= 0 THEN
        RAISE EXCEPTION 'Purchase quantity must be positive';
    END IF;

    SELECT * INTO listing
    FROM public.produce_listings
    WHERE id = p_listing_id AND status = 'available'
    FOR UPDATE;

    IF NOT FOUND OR p_quantity_kg > listing.quantity_kg THEN
        RAISE EXCEPTION 'Listing unavailable or requested quantity exceeds stock';
    END IF;

    INSERT INTO public.produce_purchase_requests (
        listing_id, buyer_name, buyer_phone, seller_name, seller_phone,
        crop_name, quantity_kg, price_per_kg, total_amount
    ) VALUES (
        listing.id, trim(p_buyer_name), trim(p_buyer_phone), listing.seller_name, listing.seller_phone,
        listing.crop_name, p_quantity_kg, listing.price_per_kg, p_quantity_kg * listing.price_per_kg
    ) RETURNING id INTO request_id;

    remaining := listing.quantity_kg - p_quantity_kg;
    UPDATE public.produce_listings
    SET quantity_kg = remaining,
        status = CASE WHEN remaining = 0 THEN 'sold' ELSE 'available' END,
        updated_at = CURRENT_TIMESTAMP
    WHERE id = listing.id;

    RETURN jsonb_build_object(
        'request_id', request_id,
        'listing_id', listing.id,
        'crop_name', listing.crop_name,
        'quantity_kg', p_quantity_kg,
        'price_per_kg', listing.price_per_kg,
        'total_amount', p_quantity_kg * listing.price_per_kg,
        'seller_name', listing.seller_name,
        'seller_phone', listing.seller_phone,
        'buyer_name', trim(p_buyer_name),
        'buyer_phone', trim(p_buyer_phone),
        'remaining_quantity_kg', remaining,
        'status', 'requested'
    );
END;
$$;

REVOKE ALL ON FUNCTION public.request_produce_purchase(UUID, TEXT, TEXT, NUMERIC) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.request_produce_purchase(UUID, TEXT, TEXT, NUMERIC) TO service_role;
