-- =====================================================================
-- AgriSmart AI - Complete Supabase PostgreSQL Database Schema & Seed Script
-- Copy and Paste this entire file into Supabase Dashboard -> SQL Editor and click RUN
-- =====================================================================

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL DEFAULT 'Farmer',
    phone VARCHAR(50) UNIQUE NOT NULL,
    preferred_language VARCHAR(10) DEFAULT 'en',
    verified BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Farms Parcel Table
CREATE TABLE IF NOT EXISTS public.farms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    farm_name VARCHAR(255) NOT NULL,
    acreage NUMERIC(5,2) NOT NULL DEFAULT 2.50,
    latitude NUMERIC(9,6) NOT NULL,
    longitude NUMERIC(9,6) NOT NULL,
    pincode VARCHAR(10) NOT NULL,
    village VARCHAR(255) NOT NULL,
    mandal VARCHAR(255),
    district VARCHAR(255) NOT NULL,
    state VARCHAR(255) DEFAULT 'Andhra Pradesh',
    survey_number VARCHAR(100),
    soil_ph NUMERIC(3,1),
    soil_ph_updated_at TIMESTAMP WITH TIME ZONE,
    soil_type VARCHAR(100) DEFAULT 'Loamy',
    water_availability VARCHAR(100) DEFAULT 'Moderate',
    recent_rainfall VARCHAR(100) DEFAULT '42 mm (last 30 days)',
    current_season VARCHAR(100) DEFAULT 'Kharif (Jun - Sep)',
    previous_crops VARCHAR(255) DEFAULT 'Paddy, Maize',
    recent_fertilizers VARCHAR(255) DEFAULT 'Urea, DAP',
    irrigation_method VARCHAR(100) DEFAULT 'Drip / Canal',
    current_crops VARCHAR(255) DEFAULT 'Paddy',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Farm Soil Records Table
CREATE TABLE IF NOT EXISTS public.farm_soil_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT REFERENCES public.farms(id) ON DELETE CASCADE,
    ph NUMERIC(3,1) NOT NULL,
    measurement_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    measurement_source VARCHAR(255) DEFAULT 'Soil Testing Lab',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Weather Cache Table
CREATE TABLE IF NOT EXISTS public.weather_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT REFERENCES public.farms(id) ON DELETE CASCADE,
    village VARCHAR(255) NOT NULL,
    district VARCHAR(255),
    state VARCHAR(255),
    latitude NUMERIC(9,6) NOT NULL,
    longitude NUMERIC(9,6) NOT NULL,
    current_temp INTEGER NOT NULL,
    feels_like INTEGER,
    condition VARCHAR(100) NOT NULL,
    rain_chance INTEGER NOT NULL,
    max_temp INTEGER NOT NULL,
    min_temp INTEGER NOT NULL,
    wind_speed INTEGER NOT NULL,
    humidity INTEGER NOT NULL,
    forecast_json JSONB NOT NULL,
    insights_json JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. AI Conversation History Table
CREATE TABLE IF NOT EXISTS public.ai_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    farm_id BIGINT REFERENCES public.farms(id) ON DELETE SET NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    language VARCHAR(10) DEFAULT 'en',
    audio_available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. Weather Alerts Table
CREATE TABLE IF NOT EXISTS public.weather_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id BIGINT REFERENCES public.farms(id) ON DELETE CASCADE,
    risk_type VARCHAR(100) NOT NULL,
    severity VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    recommendation TEXT,
    metric VARCHAR(100),
    forecast_window VARCHAR(100),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. Saved Farmer Items Table
CREATE TABLE IF NOT EXISTS public.saved_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    farm_id BIGINT REFERENCES public.farms(id) ON DELETE SET NULL,
    item_type VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    metadata_json JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create Indexes for Optimal Query Performance
CREATE INDEX IF NOT EXISTS idx_farms_user_id ON public.farms(user_id);
CREATE INDEX IF NOT EXISTS idx_weather_cache_farm_id ON public.weather_cache(farm_id);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_user_id ON public.ai_conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_soil_records_farm_id ON public.farm_soil_records(farm_id);
CREATE INDEX IF NOT EXISTS idx_alerts_farm_id ON public.weather_alerts(farm_id);

-- Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.farms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weather_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.farm_soil_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weather_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_items ENABLE ROW LEVEL SECURITY;

-- Permissive public access policies for development
CREATE POLICY "Public Read Access" ON public.users FOR SELECT USING (true);
CREATE POLICY "Public Insert Access" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Read Access" ON public.farms FOR SELECT USING (true);
CREATE POLICY "Public Insert Access" ON public.farms FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Access" ON public.farms FOR UPDATE USING (true);
CREATE POLICY "Public Delete Access" ON public.farms FOR DELETE USING (true);

-- Seed Initial Farmer User
INSERT INTO public.users (name, phone, preferred_language, verified)
VALUES ('Ramesh Kumar', '+919876543210', 'en', true)
ON CONFLICT (phone) DO UPDATE SET name = EXCLUDED.name
RETURNING *;

-- Seed Initial Farm Parcels
INSERT INTO public.farms (user_id, farm_name, acreage, latitude, longitude, pincode, village, mandal, district, state, soil_ph, soil_type, water_availability, current_crops)
VALUES
(1, 'Bhimavaram Farm', 2.50, 16.544900, 81.521200, '534201', 'Bhimavaram', 'Bhimavaram', 'West Godavari', 'Andhra Pradesh', 6.5, 'Loamy', 'Moderate', 'Paddy'),
(1, 'Tanuku Farm', 1.75, 16.758800, 81.696100, '534211', 'Tanuku', 'Tanuku', 'West Godavari', 'Andhra Pradesh', 6.8, 'Clay', 'High', 'Paddy'),
(1, 'Narsapuram Farm', 3.00, 16.438900, 81.688300, '534275', 'Narsapuram', 'Narsapuram', 'West Godavari', 'Andhra Pradesh', 7.1, 'Alluvial', 'High', 'Sugarcane')
ON CONFLICT DO NOTHING;
