-- Store each irrigation response, including field observations, pest guidance,
-- Gemini fertilizer recommendations, and the complete crop-cycle plan.
CREATE TABLE IF NOT EXISTS public.irrigation_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_farm_id BIGINT NOT NULL,
    crop VARCHAR(80) NOT NULL,
    water_source VARCHAR(80) NOT NULL,
    growth_stage VARCHAR(100) NOT NULL,
    crop_duration_days INTEGER,
    language VARCHAR(10) NOT NULL DEFAULT 'en',
    field_update_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    ai_status VARCHAR(80) NOT NULL,
    plan_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_irrigation_plans_farm_created
    ON public.irrigation_plans (local_farm_id, created_at DESC);

ALTER TABLE public.irrigation_plans ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.irrigation_plans FROM anon, authenticated;
GRANT ALL ON public.irrigation_plans TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.irrigation_plans_id_seq TO service_role;
